version: 2.1
orbs:
  node: circleci/node@4.7.0
workflows:
  matrix-tests:
    jobs:
      - node/test:
          pkg-manager: yarn
          matrix:
            parameters:
              version:
                - 12.22.6
                - 14.17.6
                - 16.8.0
