version: 2.1
orbs:
  node: circleci/node@4.7.0
workflows:
  matrix-tests:
    jobs:
      - node/test:
          pkg-manager: yarn
          matrix:
            parameters:
              version:
                - 12.22.12
                - 14.19.1
                - 16.14.2
                - 17.9.0
                - 18.2.0
