version: 2.1
orbs:
  node: circleci/node@4.4.0
workflows:
  matrix-tests:
    jobs:
      - node/test:
          pkg-manager: yarn
          matrix:
            parameters:
              version:
                - 12.22.1
                - 14.17.0
                - 16.2.0
