version: 2.1
orbs:
  node: circleci/node@4.5.1
workflows:
  matrix-tests:
    jobs:
      - node/test:
          pkg-manager: yarn
          matrix:
            parameters:
              version:
                - 12.22.4
                - 14.17.4
                - 16.6.0
